name: Build GDExtension
on:
  workflow_call:
  workflow_dispatch:
  push:
  pull_request:
  merge_group:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            { platform: linux, arch: x86_64, os: ubuntu-22.04, mruby_config: '', mruby_build: host, windows_compiler: mingw },
            { platform: windows, arch: x86_64, os: windows-latest, mruby_config: '', mruby_build: host, windows_compiler: msvc },
            { platform: macos, arch: universal, os: macos-latest, mruby_config: '', mruby_build: host, windows_compiler: mingw },
            { platform: android, arch: arm64, os: ubuntu-22.04, mruby_config: 'android_arm64', mruby_build: 'android-arm64-v8a', windows_compiler: mingw },
            { platform: ios, arch: arm64, os: macos-latest, mruby_config: 'ios_arm64', mruby_build: 'ios-arm64', windows_compiler: mingw }
          ]
        target-type: [template_debug, template_release]

    runs-on: ${{ matrix.target.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.target.platform }}
          windows-compiler: ${{ matrix.target.windows_compiler }}
          em-version: 3.1.62

      - name: Install Ruby tools
        shell: bash
        run: gem install rake dotenv --no-document

      - name: Cache .scons_cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.scons-cache/
          key: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.target-type }}_cache

      - name: Build mruby
        shell: bash
        run: |
          if [ -n "${{ matrix.target.mruby_config }}" ]; then
            cd mruby
            MRUBY_CONFIG=../../build_config/${{ matrix.target.mruby_config }} rake
          else
            rake mruby_build
          fi

      - name: Build GDExtension
        shell: bash
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
        run: |
          scons \
            target=${{ matrix.target-type }} \
            platform=${{ matrix.target.platform }} \
            arch=${{ matrix.target.arch }} \
            mruby_build=${{ matrix.target.mruby_build }}

      - name: Mac Sign
        if: ${{ matrix.target.platform == 'macos' && env.APPLE_CERT_BASE64 }}
        env:
          APPLE_CERT_BASE64: ${{ secrets.APPLE_CERT_BASE64 }}
        uses: ./.github/actions/sign
        with:
          FRAMEWORK_PATH: demo/addons/redscribe/bin/macos/macos.framework
          APPLE_CERT_BASE64: ${{ secrets.APPLE_CERT_BASE64 }}
          APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
          APPLE_DEV_PASSWORD: ${{ secrets.APPLE_DEV_PASSWORD }}
          APPLE_DEV_ID: ${{ secrets.APPLE_DEV_ID }}
          APPLE_DEV_TEAM_ID: ${{ secrets.APPLE_DEV_TEAM_ID }}
          APPLE_DEV_APP_ID: ${{ secrets.APPLE_DEV_APP_ID }}

      - name: Upload platform binaries
        uses: actions/upload-artifact@v4
        with:
          name: redscribe-bin-${{ matrix.target.platform }}-${{ matrix.target.arch }}-${{ matrix.target-type }}
          path: |
            ${{ github.workspace }}/demo/addons/redscribe/bin/${{ matrix.target.platform }}/**
          if-no-files-found: error

  package:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install Ruby tools
        shell: bash
        run: gem install rake dotenv --no-document

      - name: Download platform binaries
        uses: actions/download-artifact@v4
        with:
          pattern: redscribe-bin-*
          merge-multiple: true
          path: demo/addons/redscribe/bin

      - name: Package addon
        shell: bash
        run: rake package

      - name: Upload addon package
        uses: actions/upload-artifact@v4
        with:
          name: redscribe-addon-package
          path: |
            ${{ github.workspace }}/tmp/addons.tar.gz
          if-no-files-found: error
